version: "3.8"

networks:
  trackpoint-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: trackpoint
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./resources/mysql-data:/data
    networks:
      - trackpoint-network

  redis:
    image: redislabs/rebloom:latest
    ports:
      - "6379:6379"
    networks:
      - trackpoint-network
    environment:
      TZ: Asia/Shanghai

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # 数据操作端口
      - "9001:9001" # 控制台端口
    networks:
      - trackpoint-network
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      TZ: Asia/Shanghai
    command: server /data --console-address ":9000" --address ":9001" # webui

  server:
    image: python:3.11.9-alpine3.20
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
      - minio
    networks:
      - trackpoint-network
    volumes:
      - .:/app # 本地开发
    environment:
      TZ: Asia/Shanghai
      DOCKER: true
    command: sh -c "cd app && pip install -r requirements.txt && python main.py"
