

networks:
  trackpoint-network:
    driver: bridge

services:

  mysql:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: trackpoint
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./resource/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trackpoint-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      timeout: 20s

  redis:
    image: redislabs/rebloom:latest
    ports:
      - "6379:6379"
    networks:
      - trackpoint-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # 数据操作端口
      - "9001:9001" # 控制台端口
    networks:
      - trackpoint-network
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9000" --address ":9001" # 不配置外面打不开

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
      - minio
    networks:
      - trackpoint-network
    volumes:
      - .:/app # 本地开发
